// Generated by CoffeeScript 1.12.4
var assertValid, cloneObject, recursiveClone;

assertValid = require("assertValid");

cloneObject = function(obj, recursive) {
  var clone;
  assertValid(obj, "object");
  assertValid(recursive, "boolean?");
  clone = obj.constructor !== null ? {} : Object.create(null);
  if (recursive) {
    return recursiveClone(clone, obj);
  } else {
    return Object.assign(clone, obj);
  }
};

module.exports = cloneObject;

recursiveClone = function(clone, obj) {
  var key, value;
  for (key in obj) {
    value = obj[key];
    clone[key] = value && value.constructor === Object ? recursiveClone({}, value) : value;
  }
  return clone;
};
